export { default as About } from "./About";
export { default as Home } from "./Home";
export { default as Hero } from "./Hero";
export { default as Navbar } from "./Navbar";
export { default as Skills } from "./Skills";
export { default as Portfolio } from "./Portfolio";
export { default as Testimonials } from "./Testimonials";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
